version: '3.8'

services:
  worker:
    build:
      context: ".."
      dockerfile: "scripts/Dockerfile.worker"
    networks:
      hotstuff:

  controller:
    build:
      context: ".."
      dockerfile: "scripts/Dockerfile.controller"
    networks:
      hotstuff:
    entrypoint: sleep infinity

networks:
  hotstuff:
    ipam:
      config:
        - subnet: "192.168.1.0/24"
